/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

/**
 *
 * @author lenovo
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        buttonBack = new javax.swing.JButton();
        buttonBProfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContact = new javax.swing.JPanel();
        labelContact5 = new javax.swing.JLabel();
        labelContact6 = new javax.swing.JLabel();
        labelContact7 = new javax.swing.JLabel();
        labelContact8 = new javax.swing.JLabel();
        labelContact9 = new javax.swing.JLabel();
        labelCarpoolLogo = new javax.swing.JLabel();
        panelLoginFrame = new javax.swing.JPanel();
        labelLOGIN = new javax.swing.JLabel();
        textfieldUsername1 = new javax.swing.JTextField();
        textfieldPassword = new javax.swing.JTextField();
        labelForgotPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        buttonRegister = new javax.swing.JButton();
        labelWhiteLineDivider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(102, 142, 57));
        panelMain.setToolTipText("");
        panelMain.setPreferredSize(new java.awt.Dimension(1270, 720));

        buttonBack.setBackground(new java.awt.Color(102, 142, 57));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/backIcon.png"))); // NOI18N

        buttonBProfile.setBackground(new java.awt.Color(102, 142, 57));
        buttonBProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/profiledashboardIcon.png"))); // NOI18N

        panelContact.setBackground(new java.awt.Color(102, 142, 57));

        labelContact5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact5.setForeground(new java.awt.Color(255, 255, 255));
        labelContact5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/fbIcon.png"))); // NOI18N
        labelContact5.setText("www.facebook/sahayatri_carpool.com");

        labelContact6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/contactIcon.png"))); // NOI18N

        labelContact7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact7.setForeground(new java.awt.Color(255, 255, 255));
        labelContact7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/phoneIcon.PNG"))); // NOI18N
        labelContact7.setText("+977-(01)-4797486, +977-9841446531");

        labelContact8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact8.setForeground(new java.awt.Color(255, 255, 255));
        labelContact8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/locationIcon.png"))); // NOI18N
        labelContact8.setText("Pipolbot, Dillibazar, Kathmandu");

        labelContact9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact9.setForeground(new java.awt.Color(255, 255, 255));
        labelContact9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/emailIcon.png"))); // NOI18N
        labelContact9.setText("sahayatri.carpool@gmail.com");

        labelCarpoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/carpoolsmall.png"))); // NOI18N

        panelLoginFrame.setBackground(new java.awt.Color(102, 142, 57));

        labelLOGIN.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        labelLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        labelLOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLOGIN.setText("EDIT PROFILE ");

        textfieldUsername1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldUsername1.setText("Username");
        textfieldUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldUsername1ActionPerformed(evt);
            }
        });

        textfieldPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldPassword.setText("Password");
        textfieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPasswordActionPerformed(evt);
            }
        });

        labelForgotPassword.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelForgotPassword.setForeground(new java.awt.Color(255, 0, 0));
        labelForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelForgotPassword.setText("* forgot  password?");

        buttonLogin.setBackground(new java.awt.Color(0, 0, 255));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("LOGIN");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(0, 255, 51));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("REGISTER");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        labelWhiteLineDivider.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteLineDivider.setOpaque(true);

        javax.swing.GroupLayout panelLoginFrameLayout = new javax.swing.GroupLayout(panelLoginFrame);
        panelLoginFrame.setLayout(panelLoginFrameLayout);
        panelLoginFrameLayout.setHorizontalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
            .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginFrameLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelLOGIN)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLoginFrameLayout.setVerticalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                .addGap(0, 131, Short.MAX_VALUE)
                .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textfieldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(textfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelContact6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelContact9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(panelContactLayout.createSequentialGroup()
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContactLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(labelCarpoolLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContactLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(labelContact7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1101, Short.MAX_VALUE)))
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCarpoolLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContact6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                    .addContainerGap(855, Short.MAX_VALUE)
                    .addComponent(labelContact7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jScrollPane1.setViewportView(panelContact);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(1148, 1148, 1148)
                        .addComponent(buttonBProfile)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBProfile)
                    .addComponent(buttonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername1ActionPerformed

    private void textfieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPasswordActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBProfile;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCarpoolLogo;
    private javax.swing.JLabel labelContact5;
    private javax.swing.JLabel labelContact6;
    private javax.swing.JLabel labelContact7;
    private javax.swing.JLabel labelContact8;
    private javax.swing.JLabel labelContact9;
    private javax.swing.JLabel labelForgotPassword;
    private javax.swing.JLabel labelLOGIN;
    private javax.swing.JLabel labelWhiteLineDivider;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelLoginFrame;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textfieldPassword;
    private javax.swing.JTextField textfieldUsername1;
    // End of variables declaration//GEN-END:variables
}
