/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DriverController;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import static java.lang.String.format;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import controller.UserController;
/**
 *
 * @author lenovo
 */
public class KYC extends javax.swing.JFrame {

    /**
     * Creates new form KYC
     */
    public KYC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelCarpoolLogo = new javax.swing.JLabel();
        labelWhiteLineDivider = new javax.swing.JLabel();
        panelLoginFrame = new javax.swing.JPanel();
        labelKYC = new javax.swing.JLabel();
        buttonUploadCitizenship = new javax.swing.JButton();
        buttonSubmitCitizenship = new javax.swing.JButton();
        buttonUploadCitizenship1 = new javax.swing.JButton();
        buttonSubmitCitizenship1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuBack = new javax.swing.JMenu();
        jMenuProfile = new javax.swing.JMenu();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();
        AboutUsMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(102, 142, 57));
        panelMain.setToolTipText("");
        panelMain.setPreferredSize(new java.awt.Dimension(1400, 720));

        labelCarpoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpool.png"))); // NOI18N

        labelWhiteLineDivider.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteLineDivider.setOpaque(true);

        panelLoginFrame.setBackground(new java.awt.Color(102, 142, 57));

        labelKYC.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        labelKYC.setForeground(new java.awt.Color(255, 255, 255));
        labelKYC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKYC.setText("KYC");

        buttonUploadCitizenship.setBackground(new java.awt.Color(0, 0, 255));
        buttonUploadCitizenship.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonUploadCitizenship.setForeground(new java.awt.Color(255, 255, 255));
        buttonUploadCitizenship.setText("Upload Citizenship");
        buttonUploadCitizenship.setPreferredSize(new java.awt.Dimension(172, 27));
        buttonUploadCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUploadCitizenshipActionPerformed(evt);
            }
        });

        buttonSubmitCitizenship.setBackground(new java.awt.Color(0, 255, 51));
        buttonSubmitCitizenship.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSubmitCitizenship.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmitCitizenship.setText("Submit Citizenship");
        buttonSubmitCitizenship.setPreferredSize(new java.awt.Dimension(172, 27));
        buttonSubmitCitizenship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitCitizenshipMouseClicked(evt);
            }
        });
        buttonSubmitCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitCitizenshipActionPerformed(evt);
            }
        });

        buttonUploadCitizenship1.setBackground(new java.awt.Color(0, 0, 255));
        buttonUploadCitizenship1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonUploadCitizenship1.setForeground(new java.awt.Color(255, 255, 255));
        buttonUploadCitizenship1.setText("Upload Driver License");
        buttonUploadCitizenship1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUploadCitizenship1ActionPerformed(evt);
            }
        });

        buttonSubmitCitizenship1.setBackground(new java.awt.Color(0, 255, 51));
        buttonSubmitCitizenship1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSubmitCitizenship1.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmitCitizenship1.setText("Submit Driver License");
        buttonSubmitCitizenship1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitCitizenship1ActionPerformed(evt);
            }
        });

        jLabel1.setOpaque(true);

        jLabel2.setOpaque(true);

        javax.swing.GroupLayout panelLoginFrameLayout = new javax.swing.GroupLayout(panelLoginFrame);
        panelLoginFrame.setLayout(panelLoginFrameLayout);
        panelLoginFrameLayout.setHorizontalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginFrameLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                            .addComponent(buttonUploadCitizenship1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSubmitCitizenship1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                            .addComponent(buttonUploadCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSubmitCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginFrameLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelKYC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        panelLoginFrameLayout.setVerticalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginFrameLayout.createSequentialGroup()
                .addComponent(labelKYC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUploadCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubmitCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSubmitCitizenship1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUploadCitizenship1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelCarpoolLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCarpoolLogo))))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jMenuBack.setBackground(new java.awt.Color(102, 142, 57));
        jMenuBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBack.setForeground(new java.awt.Color(255, 0, 102));
        jMenuBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backIcon.png"))); // NOI18N
        jMenuBack.setText("BACK");
        jMenuBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBack.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuBack.setOpaque(true);
        jMenuBack.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBackMouseClicked(evt);
            }
        });
        jMenu.add(jMenuBack);

        jMenuProfile.setBackground(new java.awt.Color(102, 142, 57));
        jMenuProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profiledashboardIcon.png"))); // NOI18N
        jMenuProfile.setText("Profile");
        jMenuProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuProfile.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuProfile.setOpaque(true);
        jMenuProfile.setPreferredSize(new java.awt.Dimension(200, 52));

        jMenuItemDelete.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItemDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemDelete.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete.png"))); // NOI18N
        jMenuItemDelete.setText("Delete Account");
        jMenuItemDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItemDelete.setOpaque(true);
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItemDelete);

        jMenu.add(jMenuProfile);

        jMenu1.setBackground(new java.awt.Color(102, 142, 57));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(400, 6));
        jMenu.add(jMenu1);

        contactMenu.setBackground(new java.awt.Color(102, 142, 57));
        contactMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contactMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/HelpIcon.png"))); // NOI18N
        contactMenu.setText("Help");
        contactMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        contactMenu.setMinimumSize(new java.awt.Dimension(200, 52));
        contactMenu.setOpaque(true);
        contactMenu.setPreferredSize(new java.awt.Dimension(200, 52));
        contactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMenuMouseClicked(evt);
            }
        });

        AboutUsMenuItem.setBackground(new java.awt.Color(102, 142, 57));
        AboutUsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/AboutUs.png"))); // NOI18N
        AboutUsMenuItem.setText("About Us");
        AboutUsMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AboutUsMenuItem.setOpaque(true);
        AboutUsMenuItem.setPreferredSize(new java.awt.Dimension(200, 52));
        AboutUsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMenuItemMouseClicked(evt);
            }
        });
        AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsMenuItemActionPerformed(evt);
            }
        });
        contactMenu.add(AboutUsMenuItem);

        jMenuItem2.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TermsIcon.png"))); // NOI18N
        jMenuItem2.setText("Terms & Conditions");
        jMenuItem2.setOpaque(true);
        jMenuItem2.setPreferredSize(new java.awt.Dimension(400, 52));
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem2);

        jMenuItem1.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/contactIcon.png"))); // NOI18N
        jMenuItem1.setText("Contact");
        jMenuItem1.setBorderPainted(false);
        jMenuItem1.setOpaque(true);
        jMenuItem1.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem1);

        jMenu.add(contactMenu);

        jMenuLogout.setBackground(new java.awt.Color(102, 142, 57));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        jMenuLogout.setText("Logout");
        jMenuLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuLogout.setOpaque(true);
        jMenuLogout.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenu.add(jMenuLogout);

        jMenuExit.setBackground(new java.awt.Color(102, 142, 57));
        jMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuExit.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuExit.setOpaque(true);
        jMenuExit.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenu.add(jMenuExit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUploadCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadCitizenshipActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("files", ImageIO.getReaderFileSuffixes());
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
     
        /*.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jLabel1.setIcon(new ImageIcon(f.toString()));
        filename=f.getAbsolutePath();*/
        
        try{
            BufferedImage img = null;
            img = ImageIO.read(new File(f.getAbsolutePath())); 
            Image img1 = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(img1);
            jLabel1.setIcon(format);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        /*try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
                for(int readNum; (readNum = fis.read(buf)) !=-1;){
                    bos.write(buf, 0, readNum);
                }
                    photo = bos.toByteArray();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_buttonUploadCitizenshipActionPerformed

    private void buttonSubmitCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubmitCitizenshipActionPerformed

    private void buttonUploadCitizenship1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadCitizenship1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("files", ImageIO.getReaderFileSuffixes());
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        /*JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        jLabel2.setIcon(new ImageIcon(f.toString()));
        filename=f.getAbsolutePath();*/
        
        try{
            BufferedImage img = null;
            img = ImageIO.read(new File(f.getAbsolutePath())); 
            Image img1 = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(img1);
            jLabel2.setIcon(format);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonUploadCitizenship1ActionPerformed

    private void buttonSubmitCitizenship1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitCitizenship1ActionPerformed
     // TODO add your handling code here:
     JOptionPane.showMessageDialog(this, "Driver details inserted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonSubmitCitizenship1ActionPerformed

    private void buttonSubmitCitizenshipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubmitCitizenshipMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonSubmitCitizenshipMouseClicked

    private void jMenuBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBackMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuBackMouseClicked

    private void AboutUsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_AboutUsMenuItemMouseClicked

    private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_AboutUsMenuItemActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Terms().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ContactMain().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMenuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_contactMenuMouseClicked

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogoutMouseClicked
        new UserController().changeStatus(null);
        dispose();
        new Login().setVisible(true);

    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
        // TODO add your handling code here:
            UserController uc = new UserController();
            DriverController dc=  new DriverController();
            dc.cancelAllRide();
            dc.deleteallDetails();
            int result = uc.deleteAccount();
            if(result>0){
                JOptionPane.showMessageDialog(null, "Account Deleted");
                dispose();
                new Login().setVisible(true);
            }
    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

  
        
                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KYC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsMenuItem;
    private javax.swing.JButton buttonSubmitCitizenship;
    private javax.swing.JButton buttonSubmitCitizenship1;
    private javax.swing.JButton buttonUploadCitizenship;
    private javax.swing.JButton buttonUploadCitizenship1;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuBack;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuProfile;
    private javax.swing.JLabel labelCarpoolLogo;
    private javax.swing.JLabel labelKYC;
    private javax.swing.JLabel labelWhiteLineDivider;
    private javax.swing.JPanel panelLoginFrame;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename;
 
}
