/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMain = new javax.swing.JPanel();
        labelCarpoolLogo1 = new javax.swing.JLabel();
        labelWhiteLineDivider1 = new javax.swing.JLabel();
        panelLoginFrame1 = new javax.swing.JPanel();
        labelLOGIN1 = new javax.swing.JLabel();
        textfieldUsername2 = new javax.swing.JTextField();
        textfieldPassword1 = new javax.swing.JTextField();
        labelForgotPassword1 = new javax.swing.JLabel();
        buttonLogin1 = new javax.swing.JButton();
        buttonRegister1 = new javax.swing.JButton();
        panelContact = new javax.swing.JPanel();
        labelContact10 = new javax.swing.JLabel();
        labelContact11 = new javax.swing.JLabel();
        labelContact12 = new javax.swing.JLabel();
        labelContact13 = new javax.swing.JLabel();
        labelContact14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAHAYATRI CARPOOL");
        setMaximumSize(new java.awt.Dimension(1270, 720));
        setName("frameLogin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1270, 720));

        panelMain.setBackground(new java.awt.Color(102, 142, 57));
        panelMain.setToolTipText("");
        panelMain.setPreferredSize(new java.awt.Dimension(1270, 720));

        labelCarpoolLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpool.png"))); // NOI18N

        labelWhiteLineDivider1.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteLineDivider1.setOpaque(true);

        panelLoginFrame1.setBackground(new java.awt.Color(102, 142, 57));

        labelLOGIN1.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        labelLOGIN1.setForeground(new java.awt.Color(255, 255, 255));
        labelLOGIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLOGIN1.setText("LOGIN");

        textfieldUsername2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldUsername2.setText("Username");
        textfieldUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldUsername2ActionPerformed(evt);
            }
        });

        textfieldPassword1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldPassword1.setText("Password");
        textfieldPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPassword1ActionPerformed(evt);
            }
        });

        labelForgotPassword1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelForgotPassword1.setForeground(new java.awt.Color(255, 0, 0));
        labelForgotPassword1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelForgotPassword1.setText("* forgot  password?");

        buttonLogin1.setBackground(new java.awt.Color(0, 0, 255));
        buttonLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogin1.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin1.setText("LOGIN");
        buttonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogin1ActionPerformed(evt);
            }
        });

        buttonRegister1.setBackground(new java.awt.Color(0, 255, 51));
        buttonRegister1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegister1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister1.setText("REGISTER");
        buttonRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginFrame1Layout = new javax.swing.GroupLayout(panelLoginFrame1);
        panelLoginFrame1.setLayout(panelLoginFrame1Layout);
        panelLoginFrame1Layout.setHorizontalGroup(
            panelLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(panelLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginFrame1Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(panelLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelLOGIN1)
                        .addComponent(buttonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelForgotPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
        panelLoginFrame1Layout.setVerticalGroup(
            panelLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
            .addGroup(panelLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelLOGIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textfieldUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(textfieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelForgotPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        panelContact.setBackground(new java.awt.Color(102, 142, 57));

        labelContact10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact10.setForeground(new java.awt.Color(255, 255, 255));
        labelContact10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fbIcon.png"))); // NOI18N
        labelContact10.setText("www.facebook/sahayatri_carpool.com");

        labelContact11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/contactIcon.png"))); // NOI18N

        labelContact12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact12.setForeground(new java.awt.Color(255, 255, 255));
        labelContact12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/phoneIcon.PNG"))); // NOI18N
        labelContact12.setText("+977-(01)-4797486, +977-9841446531");

        labelContact13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact13.setForeground(new java.awt.Color(255, 255, 255));
        labelContact13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/locationIcon.png"))); // NOI18N
        labelContact13.setText("Pipolbot, Dillibazar, Kathmandu");

        labelContact14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact14.setForeground(new java.awt.Color(255, 255, 255));
        labelContact14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/emailIcon.png"))); // NOI18N
        labelContact14.setText("sahayatri.carpool@gmail.com");

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(labelContact14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact10, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact13, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(labelContact11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1154, Short.MAX_VALUE)))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(labelContact12, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(851, Short.MAX_VALUE)))
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContact14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelContact11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(labelContact12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelCarpoolLogo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelWhiteLineDivider1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(panelLoginFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCarpoolLogo1)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelWhiteLineDivider1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelLoginFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jScrollPane1.setViewportView(panelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getAccessibleContext().setAccessibleDescription("Login Page");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername2ActionPerformed

    private void textfieldPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPassword1ActionPerformed

    private void buttonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogin1ActionPerformed

    private void buttonRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegister1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegister1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin1;
    private javax.swing.JButton buttonRegister1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCarpoolLogo1;
    private javax.swing.JLabel labelContact10;
    private javax.swing.JLabel labelContact11;
    private javax.swing.JLabel labelContact12;
    private javax.swing.JLabel labelContact13;
    private javax.swing.JLabel labelContact14;
    private javax.swing.JLabel labelForgotPassword1;
    private javax.swing.JLabel labelLOGIN1;
    private javax.swing.JLabel labelWhiteLineDivider1;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelLoginFrame1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textfieldPassword1;
    private javax.swing.JTextField textfieldUsername2;
    // End of variables declaration//GEN-END:variables
}
