/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import controller.UserController;
import model.User;

/**
 *
 * @author lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        labelCarpoolLogo = new javax.swing.JLabel();
        labelWhiteLineDivider = new javax.swing.JLabel();
        panelLoginFrame = new javax.swing.JPanel();
        labelLOGIN = new javax.swing.JLabel();
        textfieldEmail = new javax.swing.JTextField();
        textfieldPassword = new javax.swing.JTextField();
        buttonLoginRider = new javax.swing.JButton();
        buttonRegister = new javax.swing.JButton();
        buttonLoginDriver = new javax.swing.JButton();
        buttonRegister1 = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();
        AboutUsMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAHAYATRI CARPOOL");
        setName("frameLogin"); // NOI18N

        panelMain.setBackground(new java.awt.Color(102, 142, 57));
        panelMain.setToolTipText("");
        panelMain.setPreferredSize(new java.awt.Dimension(1400, 720));

        labelCarpoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpool.png"))); // NOI18N

        labelWhiteLineDivider.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteLineDivider.setOpaque(true);

        panelLoginFrame.setBackground(new java.awt.Color(102, 142, 57));

        labelLOGIN.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        labelLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        labelLOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLOGIN.setText("LOGIN");

        textfieldEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldEmail.setText("Email");
        textfieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldEmailFocusLost(evt);
            }
        });
        textfieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldEmailActionPerformed(evt);
            }
        });

        textfieldPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldPassword.setText("Password");
        textfieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldPasswordFocusLost(evt);
            }
        });
        textfieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPasswordActionPerformed(evt);
            }
        });

        buttonLoginRider.setBackground(new java.awt.Color(0, 0, 255));
        buttonLoginRider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLoginRider.setForeground(new java.awt.Color(255, 255, 255));
        buttonLoginRider.setText("LOGIN as Rider");
        buttonLoginRider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonLoginRider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginRiderActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(0, 255, 51));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("REGISTER");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        buttonLoginDriver.setBackground(new java.awt.Color(0, 0, 255));
        buttonLoginDriver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLoginDriver.setForeground(new java.awt.Color(255, 255, 255));
        buttonLoginDriver.setText("LOGIN as Driver");
        buttonLoginDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonLoginDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginDriverMouseClicked(evt);
            }
        });
        buttonLoginDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginDriverActionPerformed(evt);
            }
        });

        buttonRegister1.setBackground(new java.awt.Color(255, 51, 51));
        buttonRegister1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        buttonRegister1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister1.setText("* Forgot Password?");
        buttonRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginFrameLayout = new javax.swing.GroupLayout(panelLoginFrame);
        panelLoginFrame.setLayout(panelLoginFrameLayout);
        panelLoginFrameLayout.setHorizontalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLOGIN)
                    .addComponent(buttonLoginRider, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLoginDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        panelLoginFrameLayout.setVerticalGroup(
            panelLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginFrameLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(labelLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(textfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLoginRider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLoginDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelCarpoolLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCarpoolLogo)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        labelCarpoolLogo.getAccessibleContext().setAccessibleName("labelCarpoolPhoto");
        labelCarpoolLogo.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setBackground(new java.awt.Color(102, 142, 57));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(1000, 6));
        jMenu.add(jMenu1);

        contactMenu.setBackground(new java.awt.Color(102, 142, 57));
        contactMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contactMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/HelpIcon.png"))); // NOI18N
        contactMenu.setText("Help");
        contactMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        contactMenu.setMinimumSize(new java.awt.Dimension(200, 52));
        contactMenu.setOpaque(true);
        contactMenu.setPreferredSize(new java.awt.Dimension(200, 52));
        contactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMenuMouseClicked(evt);
            }
        });

        AboutUsMenuItem.setBackground(new java.awt.Color(102, 142, 57));
        AboutUsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/AboutUs.png"))); // NOI18N
        AboutUsMenuItem.setText("About Us");
        AboutUsMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AboutUsMenuItem.setOpaque(true);
        AboutUsMenuItem.setPreferredSize(new java.awt.Dimension(200, 52));
        AboutUsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMenuItemMouseClicked(evt);
            }
        });
        AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsMenuItemActionPerformed(evt);
            }
        });
        contactMenu.add(AboutUsMenuItem);

        jMenuItem2.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TermsIcon.png"))); // NOI18N
        jMenuItem2.setText("Terms & Conditions");
        jMenuItem2.setOpaque(true);
        jMenuItem2.setPreferredSize(new java.awt.Dimension(400, 52));
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem2);

        jMenuItem1.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/contactIcon.png"))); // NOI18N
        jMenuItem1.setText("Contact");
        jMenuItem1.setBorderPainted(false);
        jMenuItem1.setOpaque(true);
        jMenuItem1.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem1);

        jMenu.add(contactMenu);

        jMenuExit.setBackground(new java.awt.Color(102, 142, 57));
        jMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuExit.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuExit.setOpaque(true);
        jMenuExit.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenu.add(jMenuExit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMain.getAccessibleContext().setAccessibleName("panelLogin");

        getAccessibleContext().setAccessibleDescription("Login Page");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void textfieldEmailActionPerformed(ActionEvent evt) {
    }
    private void textfieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsername1ActionPerformed

    private void textfieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPasswordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textfieldPasswordActionPerformed

    private void buttonLoginRiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginRiderActionPerformed
        // if(textfieldUsername1.)
        try {
            User u1 = new User(null, textfieldPassword.getText(), null, null, null, null, null, null, null, null, textfieldEmail.getText(), null, null, null, null, null, null) ;
             UserController sc = new UserController();
             ResultSet result = sc.selectQuery(u1);
                 if(result.next()){
                     JOptionPane.showMessageDialog(null, "Login Success");
                     sc.changeStatus(u1);
                     sc.updatestatus(u1);
                     dispose();
                     new Search().setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "Incorrect Credentials");
     
                 }
             } catch (Exception e) {
                 // TODO Auto-generated catch block
                 e.printStackTrace();
             }
    }//GEN-LAST:event_buttonLoginRiderActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void textfieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldEmailFocusGained
        // TODO add your handling code here:
        if (textfieldEmail.getText().equals("Email")) {
            textfieldEmail.setText("");
        }
    }//GEN-LAST:event_textfieldEmailFocusGained

    private void textfieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldEmailFocusLost
        // TODO add your handling code here:
        if (textfieldEmail.getText().equals("")) {
            textfieldEmail.setText("Email");
        }
    }//GEN-LAST:event_textfieldEmailFocusLost

    private void textfieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusGained
        // TODO add your handling code here:
        if (textfieldPassword.getText().equals("Password")) {
            textfieldPassword.setText("");
        }
    }//GEN-LAST:event_textfieldPasswordFocusGained

    private void textfieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPasswordFocusLost
        // TODO add your handling code here:
        if (textfieldPassword.getText().equals("")) {
            textfieldPassword.setText("Password");
        }
    }//GEN-LAST:event_textfieldPasswordFocusLost

    private void buttonLoginDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginDriverActionPerformed
        try {
            User u1 = new User(null, textfieldPassword.getText(), null, null, null, null, null, null, null, null, textfieldEmail.getText(), null, null, null, null, null, null) ;
             UserController sc = new UserController();
             ResultSet result = sc.selectQuery(u1);
                 if(result.next()){
                     JOptionPane.showMessageDialog(null, "Login Success");
                     sc.changeStatus(u1);
                     sc.updatestatus(u1);
                     dispose();
                     new seat().setVisible(true);
                     
                    }else{
                     JOptionPane.showMessageDialog(null, "Incorrect Credentials");

                 }
             } catch (Exception e) {
                 // TODO Auto-generated catch block
                 e.printStackTrace();
             }
    }//GEN-LAST:event_buttonLoginDriverActionPerformed

    private void buttonRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegister1ActionPerformed
        dispose();
        new ForgetPassword().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_buttonRegister1ActionPerformed

    private void buttonLoginDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginDriverMouseClicked
        // TODO add your handling code here:
        dispose();
        new seat().setVisible(true);
    }//GEN-LAST:event_buttonLoginDriverMouseClicked

    private void AboutUsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_AboutUsMenuItemMouseClicked

    private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_AboutUsMenuItemActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Terms().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ContactMain().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMenuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_contactMenuMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Do you want to exit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
            new UserController().changeStatus(null);
            dispose();
        }
        else if(response == JOptionPane.NO_OPTION){
           return;
            
        }

    }//GEN-LAST:event_jMenuExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonLoginDriver;
    private javax.swing.JButton buttonLoginRider;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonRegister1;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelCarpoolLogo;
    private javax.swing.JLabel labelLOGIN;
    private javax.swing.JLabel labelWhiteLineDivider;
    private javax.swing.JPanel panelLoginFrame;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textfieldEmail;
    private javax.swing.JTextField textfieldPassword;
    // End of variables declaration//GEN-END:variables
}
