/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

import controller.UserController;
import model.User;

/**
 *
 * @author lenovo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelBack = new javax.swing.JLabel();
        labelLogoTop = new javax.swing.JLabel();
        labelWhiteHLine = new javax.swing.JLabel();
        panelRegisterFrame = new javax.swing.JPanel();
        labelLOGIN = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        buttonRegister = new javax.swing.JButton();
        labelWhiteLineDivider = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelRePassword = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelDOB = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelNationality = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelSecurityQuestion = new javax.swing.JLabel();
        labelAnswer = new javax.swing.JLabel();
        labelCitizenshipNo = new javax.swing.JLabel();
        labelDriverLicenseNo = new javax.swing.JLabel();
        labelExpiryDate = new javax.swing.JLabel();
        textfieldFirstName = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        repassText = new javax.swing.JPasswordField();
        textfieldLastName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        DateDOB = new com.toedter.calendar.JDateChooser();
        textfieldNationality = new javax.swing.JTextField();
        textfieldStreet = new javax.swing.JTextField();
        textfieldEmail = new javax.swing.JTextField();
        textfieldPhone = new javax.swing.JTextField();
        textfieldAnswer = new javax.swing.JTextField();
        textfieldCitizenship = new javax.swing.JTextField();
        textfieldDriverLicense = new javax.swing.JTextField();
        DateExpiry = new com.toedter.calendar.JDateChooser();
        labelNote = new javax.swing.JLabel();
        panelContact = new javax.swing.JPanel();
        labelContact5 = new javax.swing.JLabel();
        labelContact6 = new javax.swing.JLabel();
        labelContact7 = new javax.swing.JLabel();
        labelContact8 = new javax.swing.JLabel();
        labelContact9 = new javax.swing.JLabel();
        jComboBoxSecurityQuestion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1270, 720));
        setPreferredSize(new java.awt.Dimension(1270, 720));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1270, 720));

        jPanel1.setBackground(new java.awt.Color(102, 142, 57));

        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backIcon.png"))); // NOI18N

        labelLogoTop.setBackground(new java.awt.Color(102, 142, 57));
        labelLogoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpoolsmall.png"))); // NOI18N

        labelWhiteHLine.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteHLine.setOpaque(true);
        labelWhiteHLine.setPreferredSize(new java.awt.Dimension(4, 20));

        panelRegisterFrame.setBackground(new java.awt.Color(102, 142, 57));
        panelRegisterFrame.setPreferredSize(new java.awt.Dimension(1270, 382));

        labelLOGIN.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        labelLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        labelLOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLOGIN.setText("REGISTER");
        labelLOGIN.setPreferredSize(new java.awt.Dimension(1270, 134));

        textfieldUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldUsername.setName(""); // NOI18N
        textfieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldUsernameActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(0, 255, 51));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("REGISTER");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        labelWhiteLineDivider.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteLineDivider.setOpaque(true);

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username*");
        labelUsername.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelUsername.setPreferredSize(new java.awt.Dimension(100, 22));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password*");
        labelPassword.setDoubleBuffered(true);
        labelPassword.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelPassword.setPreferredSize(new java.awt.Dimension(100, 22));

        labelRePassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRePassword.setForeground(new java.awt.Color(255, 255, 255));
        labelRePassword.setText("Re-enter Password*");
        labelRePassword.setDoubleBuffered(true);
        labelRePassword.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelRePassword.setPreferredSize(new java.awt.Dimension(100, 22));

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Name*");
        labelName.setDoubleBuffered(true);
        labelName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelName.setPreferredSize(new java.awt.Dimension(100, 22));

        labelDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDOB.setForeground(new java.awt.Color(255, 255, 255));
        labelDOB.setText("DOB*");
        labelDOB.setDoubleBuffered(true);
        labelDOB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelDOB.setPreferredSize(new java.awt.Dimension(100, 22));

        labelGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelGender.setForeground(new java.awt.Color(255, 255, 255));
        labelGender.setText("Gender*");
        labelGender.setDoubleBuffered(true);
        labelGender.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelGender.setPreferredSize(new java.awt.Dimension(100, 22));

        labelNationality.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNationality.setForeground(new java.awt.Color(255, 255, 255));
        labelNationality.setText("Nationality*");
        labelNationality.setDoubleBuffered(true);
        labelNationality.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelNationality.setPreferredSize(new java.awt.Dimension(100, 22));

        labelAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(255, 255, 255));
        labelAddress.setText("Address*");
        labelAddress.setDoubleBuffered(true);
        labelAddress.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelAddress.setPreferredSize(new java.awt.Dimension(100, 22));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail*");
        labelEmail.setDoubleBuffered(true);
        labelEmail.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelEmail.setPreferredSize(new java.awt.Dimension(100, 22));

        labelPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPhone.setForeground(new java.awt.Color(255, 255, 255));
        labelPhone.setText("Phone Number*");
        labelPhone.setDoubleBuffered(true);
        labelPhone.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelPhone.setPreferredSize(new java.awt.Dimension(100, 22));

        labelSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSecurityQuestion.setForeground(new java.awt.Color(255, 255, 255));
        labelSecurityQuestion.setText("Security Question*");
        labelSecurityQuestion.setDoubleBuffered(true);
        labelSecurityQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelSecurityQuestion.setPreferredSize(new java.awt.Dimension(100, 22));

        labelAnswer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAnswer.setForeground(new java.awt.Color(255, 255, 255));
        labelAnswer.setText("Answer*");
        labelAnswer.setDoubleBuffered(true);
        labelAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelAnswer.setPreferredSize(new java.awt.Dimension(100, 22));

        labelCitizenshipNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCitizenshipNo.setForeground(new java.awt.Color(255, 255, 255));
        labelCitizenshipNo.setText("Citizenship Number*");
        labelCitizenshipNo.setDoubleBuffered(true);
        labelCitizenshipNo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelCitizenshipNo.setPreferredSize(new java.awt.Dimension(100, 22));

        labelDriverLicenseNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDriverLicenseNo.setForeground(new java.awt.Color(255, 255, 255));
        labelDriverLicenseNo.setText("Driver License Number*");
        labelDriverLicenseNo.setDoubleBuffered(true);
        labelDriverLicenseNo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelDriverLicenseNo.setPreferredSize(new java.awt.Dimension(100, 22));

        labelExpiryDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelExpiryDate.setForeground(new java.awt.Color(255, 255, 255));
        labelExpiryDate.setText("Expiry Date");
        labelExpiryDate.setDoubleBuffered(true);
        labelExpiryDate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelExpiryDate.setPreferredSize(new java.awt.Dimension(100, 22));

        textfieldFirstName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldFirstName.setText("First Name");
        textfieldFirstName.setName(""); // NOI18N
        textfieldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldFirstNameFocusLost(evt);
            }
        });
        textfieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFirstNameActionPerformed(evt);
            }
        });

        passText.setText("Password");
        passText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFocusLost(evt);
            }
        });

        repassText.setText("Password");

        textfieldLastName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldLastName.setText("Last Name");
        textfieldLastName.setName(""); // NOI18N
        textfieldLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldLastNameFocusLost(evt);
            }
        });
        textfieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldLastNameActionPerformed(evt);
            }
        });

        MiddleName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MiddleName.setText("Middle Name");
        MiddleName.setName(""); // NOI18N
        MiddleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MiddleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MiddleNameFocusLost(evt);
            }
        });
        MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonMale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonFemale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonOther);
        jRadioButtonOther.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonOther.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonOther.setText("Other");
        jRadioButtonOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtherActionPerformed(evt);
            }
        });

        textfieldNationality.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldNationality.setText("Nepal");
        textfieldNationality.setName(""); // NOI18N
        textfieldNationality.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldNationalityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldNationalityFocusLost(evt);
            }
        });
        textfieldNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNationalityActionPerformed(evt);
            }
        });

        textfieldStreet.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldStreet.setText("Kathmandu");
        textfieldStreet.setName(""); // NOI18N
        textfieldStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldStreetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldStreetFocusLost(evt);
            }
        });
        textfieldStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldStreetActionPerformed(evt);
            }
        });

        textfieldEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldEmail.setName(""); // NOI18N
        textfieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldEmailActionPerformed(evt);
            }
        });

        textfieldPhone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldPhone.setName(""); // NOI18N
        textfieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPhoneActionPerformed(evt);
            }
        });

        textfieldAnswer.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldAnswer.setName(""); // NOI18N
        textfieldAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldAnswerActionPerformed(evt);
            }
        });

        textfieldCitizenship.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldCitizenship.setName(""); // NOI18N
        textfieldCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCitizenshipActionPerformed(evt);
            }
        });

        textfieldDriverLicense.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textfieldDriverLicense.setName(""); // NOI18N
        textfieldDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDriverLicenseActionPerformed(evt);
            }
        });

        labelNote.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelNote.setForeground(new java.awt.Color(255, 0, 0));
        labelNote.setText("* All fields with * are mandatory!");

        panelContact.setBackground(new java.awt.Color(102, 142, 57));

        labelContact5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact5.setForeground(new java.awt.Color(255, 255, 255));
        labelContact5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fbIcon.png"))); // NOI18N
        labelContact5.setText("www.facebook/sahayatri_carpool.com");

        labelContact6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/contactIcon.png"))); // NOI18N

        labelContact7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact7.setForeground(new java.awt.Color(255, 255, 255));
        labelContact7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/phoneIcon.PNG"))); // NOI18N
        labelContact7.setText("+977-(01)-4797486, +977-9841446531");

        labelContact8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact8.setForeground(new java.awt.Color(255, 255, 255));
        labelContact8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/locationIcon.png"))); // NOI18N
        labelContact8.setText("Pipolbot, Dillibazar, Kathmandu");

        labelContact9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContact9.setForeground(new java.awt.Color(255, 255, 255));
        labelContact9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/emailIcon.png"))); // NOI18N
        labelContact9.setText("sahayatri.carpool@gmail.com");

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(labelContact9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContact8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(labelContact6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1154, Short.MAX_VALUE)))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(labelContact7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(851, Short.MAX_VALUE)))
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContact9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContact5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContactLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelContact6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
            .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(labelContact7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jComboBoxSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favourite food ?", "What was your school name ?", "Who is your best friend ?", "What is your age ?", " " }));

        javax.swing.GroupLayout panelRegisterFrameLayout = new javax.swing.GroupLayout(panelRegisterFrame);
        panelRegisterFrame.setLayout(panelRegisterFrameLayout);
        panelRegisterFrameLayout.setHorizontalGroup(
            panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                        .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                                .addGap(527, 527, 527)
                                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNationality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAnswer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelExpiryDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDriverLicenseNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCitizenshipNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelSecurityQuestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNote)
                            .addComponent(textfieldDriverLicense)
                            .addComponent(textfieldCitizenship)
                            .addComponent(textfieldAnswer)
                            .addComponent(textfieldUsername)
                            .addComponent(textfieldLastName)
                            .addComponent(passText)
                            .addComponent(repassText)
                            .addComponent(jRadioButtonMale)
                            .addComponent(DateDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfieldNationality)
                            .addComponent(textfieldStreet)
                            .addComponent(textfieldEmail)
                            .addComponent(textfieldPhone)
                            .addComponent(DateExpiry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                                .addComponent(textfieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonFemale)
                            .addComponent(jRadioButtonOther)
                            .addComponent(jComboBoxSecurityQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterFrameLayout.setVerticalGroup(
            panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(textfieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(repassText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOther)
                        .addGap(22, 22, 22)
                        .addComponent(DateDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNote))
                    .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegisterFrameLayout.createSequentialGroup()
                                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(labelDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCitizenshipNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDriverLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addComponent(labelWhiteLineDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogoTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBack)
                            .addComponent(panelRegisterFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(labelWhiteHLine, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogoTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWhiteHLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegisterFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsernameActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        String username = textfieldUsername.getText();
        String fname = textfieldFirstName.getText();
        String mname= MiddleName.getText();
        String lname = textfieldLastName.getText();
        String pass = new String(passText.getPassword());
        String repass = new String(repassText.getPassword());
        String gender = null;
        if(jRadioButtonMale.isSelected()){
            gender="Male";

        }else if(jRadioButtonFemale.isSelected()){
            gender="Female";
        }
        else{
            gender ="Other";
        }

        DateFormat fmt = new SimpleDateFormat("YYYY-MM-DD");
        String dob = fmt.format(this.DateDOB.getDate());
        String nationality = textfieldNationality.getText();
        String address = textfieldStreet.getText();
        String email = textfieldEmail.getText();
        
        String phone = textfieldPhone.getText();
        String sq = jComboBoxSecurityQuestion.getSelectedItem().toString();
        String sq_ans = textfieldAnswer.getText();
        String citizen = textfieldCitizenship.getText();
        String driver_license = textfieldDriverLicense.getText();
        String exp_date = fmt.format(this.DateExpiry.getDate());
        // User u1 = new User(textfieldUsername) 
        User u1 = new User(username, pass, repass, fname, mname, lname, gender, dob, nationality, address, email, phone, sq, sq_ans, citizen, driver_license, exp_date);
        UserController sc  = new UserController();
        int result = sc.insertDetails(u1);
        JOptionPane.showMessageDialog(this, "Registered Succesfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        //dispose();
        /*if(result>0){
             JOptionPane.showMessageDialog(this, "Registered Succesfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        }else{          
             JOptionPane.showMessageDialog(this, " Registered Failed", "Error", JOptionPane.INFORMATION_MESSAGE);
            
         }*/
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void textfieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFirstNameActionPerformed

    private void textfieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldLastNameActionPerformed

    private void MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleNameActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jRadioButtonOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOtherActionPerformed

    private void textfieldNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNationalityActionPerformed

    private void textfieldStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldStreetActionPerformed

    private void textfieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldEmailActionPerformed

    private void textfieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPhoneActionPerformed

    private void textfieldAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldAnswerActionPerformed

    private void textfieldCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCitizenshipActionPerformed

    private void textfieldDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDriverLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDriverLicenseActionPerformed

    private void passTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusGained
        // TODO add your handling code here:
        /*if (passText.getPassword().equals("********")) {
            passText.setText("");
        }*/
    }//GEN-LAST:event_passTextFocusGained

    private void passTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusLost
        // TODO add your handling code here:
        /*if (passText.getPassword().equals("")) {
            passText.setText("********");
        }*/
    }//GEN-LAST:event_passTextFocusLost

    private void textfieldFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldFirstNameFocusGained
        // TODO add your handling code here:
        if (textfieldFirstName.getText().equals("First Name")) {
            textfieldFirstName.setText("");
        }
    }//GEN-LAST:event_textfieldFirstNameFocusGained

    private void textfieldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldFirstNameFocusLost
        // TODO add your handling code here:
        if (textfieldFirstName.getText().equals("")) {
            textfieldFirstName.setText("First Name");
        }
    }//GEN-LAST:event_textfieldFirstNameFocusLost

    private void MiddleNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleNameFocusGained
        // TODO add your handling code here:
        if (MiddleName.getText().equals("Middle Name")) {
            MiddleName.setText("");
        }
    }//GEN-LAST:event_MiddleNameFocusGained

    private void MiddleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleNameFocusLost
        // TODO add your handling code here:
        if (MiddleName.getText().equals("")) {
            MiddleName.setText("Middle Name");
        }
    }//GEN-LAST:event_MiddleNameFocusLost

    private void textfieldLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldLastNameFocusGained
        // TODO add your handling code here:
        if (textfieldLastName.getText().equals("Last Name")) {
            textfieldLastName.setText("");
        }
    }//GEN-LAST:event_textfieldLastNameFocusGained

    private void textfieldLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldLastNameFocusLost
        // TODO add your handling code here:
        if (textfieldLastName.getText().equals("")) {
            textfieldLastName.setText("Last Name");
        }
    }//GEN-LAST:event_textfieldLastNameFocusLost

    private void textfieldNationalityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldNationalityFocusGained
        // TODO add your handling code here:
        if (textfieldNationality.getText().equals("Nepal")) {
            textfieldNationality.setText("");
        }
    }//GEN-LAST:event_textfieldNationalityFocusGained

    private void textfieldNationalityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldNationalityFocusLost
        // TODO add your handling code here:
        if (textfieldNationality.getText().equals("")) {
            textfieldNationality.setText("Nepal");
        }
    }//GEN-LAST:event_textfieldNationalityFocusLost

    private void textfieldStreetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldStreetFocusGained
        // TODO add your handling code here:
        if (textfieldStreet.getText().equals("Kathmandu")) {
            textfieldStreet.setText("");
        }
    }//GEN-LAST:event_textfieldStreetFocusGained

    private void textfieldStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldStreetFocusLost
        // TODO add your handling code here:
        if (textfieldStreet.getText().equals("")) {
            textfieldStreet.setText("Kathmandu");
        }
    }//GEN-LAST:event_textfieldStreetFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDOB;
    private com.toedter.calendar.JDateChooser DateExpiry;
    private javax.swing.JTextField MiddleName;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JComboBox<String> jComboBoxSecurityQuestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAnswer;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelCitizenshipNo;
    private javax.swing.JLabel labelContact5;
    private javax.swing.JLabel labelContact6;
    private javax.swing.JLabel labelContact7;
    private javax.swing.JLabel labelContact8;
    private javax.swing.JLabel labelContact9;
    private javax.swing.JLabel labelDOB;
    private javax.swing.JLabel labelDriverLicenseNo;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelExpiryDate;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelLOGIN;
    private javax.swing.JLabel labelLogoTop;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNationality;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelRePassword;
    private javax.swing.JLabel labelSecurityQuestion;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelWhiteHLine;
    private javax.swing.JLabel labelWhiteLineDivider;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelRegisterFrame;
    private javax.swing.JPasswordField passText;
    private javax.swing.JPasswordField repassText;
    private javax.swing.JTextField textfieldAnswer;
    private javax.swing.JTextField textfieldCitizenship;
    private javax.swing.JTextField textfieldDriverLicense;
    private javax.swing.JTextField textfieldEmail;
    private javax.swing.JTextField textfieldFirstName;
    private javax.swing.JTextField textfieldLastName;
    private javax.swing.JTextField textfieldNationality;
    private javax.swing.JTextField textfieldPhone;
    private javax.swing.JTextField textfieldStreet;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables
}
