/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

// Importing Libraries
import controller.DriverController;
import controller.UserController;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

// import com.mysql.cj.protocol.Resultset;
// import com.mysql.cj.protocol.ResultsetRow;

import model.Driver;

/**
 *
 * @author lenovo
 */
public final class seat extends javax.swing.JFrame {

    /**
     * Creates new form EXAMPLE
     */
    public seat() {
        initComponents();
        table();
        displayBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankTop = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelProfile = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabDriverTab = new javax.swing.JPanel();
        panelEditProfile1 = new javax.swing.JPanel();
        labelLogoTop1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDriver = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Leavebox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Goingbox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Datebox = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        Trunkbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Seatbox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Pricebox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        idBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        completeBtn = new javax.swing.JButton();
        activeBtn = new javax.swing.JButton();
        fullBtn = new javax.swing.JButton();
        tabRider = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelEditProfile3 = new javax.swing.JPanel();
        labelLogoTop3 = new javax.swing.JLabel();
        labelWhiteHLine3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rideTable = new javax.swing.JTable();
        declineBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuProfile = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuKYC = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();
        AboutUsMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BankTopLayout = new javax.swing.GroupLayout(BankTop.getContentPane());
        BankTop.getContentPane().setLayout(BankTopLayout);
        BankTopLayout.setHorizontalGroup(
            BankTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BankTopLayout.setVerticalGroup(
            BankTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelProfile.setBackground(new java.awt.Color(102, 142, 57));
        panelProfile.setPreferredSize(new java.awt.Dimension(1400, 2114));

        jTabbedPane1.setBackground(new java.awt.Color(102, 142, 57));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("DRIVER");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tabDriverTab.setBackground(new java.awt.Color(102, 142, 57));

        panelEditProfile1.setBackground(new java.awt.Color(102, 142, 57));
        panelEditProfile1.setMaximumSize(new java.awt.Dimension(1145, 895));
        panelEditProfile1.setName(""); // NOI18N

        labelLogoTop1.setBackground(new java.awt.Color(102, 142, 57));
        labelLogoTop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoTop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpoolsmall.png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(102, 142, 57));

        tblDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N.", "Leaving from ....", "Going to ....", "Driver Email", "Driver Phone", "Date", "Trunk Space", "No. of Passengers", "Price", "Ride Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDriver.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDriver);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Leavebox.setEditable(true);
        Leavebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Bhaktapur", "Lalitpur", "Pokhara", "Chitwan" }));
        Leavebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveboxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Leaving from ...");

        Goingbox.setEditable(true);
        Goingbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Bhaktapur", "Lalitpur", "Pokhara", "Chitwan" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Going to ...");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Date");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Trunk Space");

        Trunkbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes ", "No" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Seat");

        Seatbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Price");

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Publish");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Leavebox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Goingbox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
<<<<<<< HEAD
                        .addComponent(Trunkbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
=======
                        .addComponent(Trunkbox, 0, 158, Short.MAX_VALUE)))
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Seatbox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pricebox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Pricebox)
                            .addComponent(Datebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Leavebox, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(Goingbox)
                            .addComponent(Trunkbox)
                            .addComponent(Seatbox))))
                .addContainerGap())
        );

        editBtn.setBackground(new java.awt.Color(102, 102, 255));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn.setText("Edit");
        editBtn.setEnabled(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDeleteFocusGained(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(51, 255, 0));
        viewBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBtn.setText("View");
        viewBtn.setMaximumSize(new java.awt.Dimension(74, 27));
        viewBtn.setMinimumSize(new java.awt.Dimension(74, 27));
        viewBtn.setPreferredSize(new java.awt.Dimension(74, 27));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        idBox.setEditable(false);
        idBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PUBLISH CARPOOL");

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RIDE STATUS");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.setOpaque(true);

        completeBtn.setBackground(new java.awt.Color(153, 0, 153));
        completeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        completeBtn.setForeground(new java.awt.Color(255, 255, 255));
        completeBtn.setText("Complete");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        activeBtn.setBackground(new java.awt.Color(51, 255, 51));
        activeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activeBtn.setForeground(new java.awt.Color(255, 255, 255));
        activeBtn.setText("Active");
        activeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeBtnActionPerformed(evt);
            }
        });

        fullBtn.setBackground(new java.awt.Color(255, 153, 0));
        fullBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullBtn.setText("Full");
        fullBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditProfile1Layout = new javax.swing.GroupLayout(panelEditProfile1);
        panelEditProfile1.setLayout(panelEditProfile1Layout);
        panelEditProfile1Layout.setHorizontalGroup(
            panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addComponent(labelLogoTop1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditProfile1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEditProfile1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelEditProfile1Layout.createSequentialGroup()
                        .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelEditProfile1Layout.createSequentialGroup()
                                        .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fullBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(110, 110, 110))))
            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                .addGap(498, 498, 498)
=======
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditProfile1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEditProfile1Layout.createSequentialGroup()
                            .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelEditProfile1Layout.createSequentialGroup()
                                    .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(21, 21, 21)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(idBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(fullBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                .addComponent(labelLogoTop1, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                .addGap(499, 499, 499)
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditProfile1Layout.setVerticalGroup(
            panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelLogoTop1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditProfile1Layout.createSequentialGroup()
<<<<<<< HEAD
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditProfile1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditProfile1Layout.createSequentialGroup()
                                .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEditProfile1Layout.createSequentialGroup()
                                        .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idBox))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1024, 1024, 1024))
                    .addGroup(panelEditProfile1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(fullBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
=======
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEditProfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(fullBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEditProfile1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(idBox))
                        .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1023, Short.MAX_VALUE))
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
        );

        javax.swing.GroupLayout tabDriverTabLayout = new javax.swing.GroupLayout(tabDriverTab);
        tabDriverTab.setLayout(tabDriverTabLayout);
        tabDriverTabLayout.setHorizontalGroup(
            tabDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(tabDriverTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEditProfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDriverTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelEditProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
        );
        tabDriverTabLayout.setVerticalGroup(
            tabDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDriverTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEditProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DRIVER", tabDriverTab);

        tabRider.setBackground(new java.awt.Color(102, 142, 57));

        jPanel5.setBackground(new java.awt.Color(102, 142, 57));

        panelEditProfile3.setBackground(new java.awt.Color(102, 142, 57));
        panelEditProfile3.setMaximumSize(new java.awt.Dimension(1145, 895));
        panelEditProfile3.setName(""); // NOI18N

        labelLogoTop3.setBackground(new java.awt.Color(102, 142, 57));
        labelLogoTop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoTop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/carpoolsmall.png"))); // NOI18N

        labelWhiteHLine3.setBackground(new java.awt.Color(255, 255, 255));
        labelWhiteHLine3.setOpaque(true);
        labelWhiteHLine3.setPreferredSize(new java.awt.Dimension(4, 20));

        rideTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SN", "From", "To", "Username", "Phone", "Book Status"
            }
        ));
        jScrollPane2.setViewportView(rideTable);

        declineBtn.setBackground(new java.awt.Color(204, 0, 0));
        declineBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        declineBtn.setForeground(new java.awt.Color(255, 255, 255));
        declineBtn.setText("Decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        acceptBtn.setBackground(new java.awt.Color(0, 153, 51));
        acceptBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acceptBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESPOND");

        javax.swing.GroupLayout panelEditProfile3Layout = new javax.swing.GroupLayout(panelEditProfile3);
        panelEditProfile3.setLayout(panelEditProfile3Layout);
        panelEditProfile3Layout.setHorizontalGroup(
            panelEditProfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditProfile3Layout.createSequentialGroup()
                .addComponent(labelLogoTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelEditProfile3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditProfile3Layout.createSequentialGroup()
                .addGap(0, 339, Short.MAX_VALUE)
                .addGroup(panelEditProfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditProfile3Layout.createSequentialGroup()
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditProfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelWhiteHLine3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(329, 329, 329))
        );
        panelEditProfile3Layout.setVerticalGroup(
            panelEditProfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditProfile3Layout.createSequentialGroup()
                .addComponent(labelLogoTop3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWhiteHLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelEditProfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(961, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditProfile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditProfile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout tabRiderLayout = new javax.swing.GroupLayout(tabRider);
        tabRider.setLayout(tabRiderLayout);
        tabRiderLayout.setHorizontalGroup(
            tabRiderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGap(0, 1384, Short.MAX_VALUE)
=======
            .addGap(0, 1387, Short.MAX_VALUE)
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
            .addGroup(tabRiderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabRiderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tabRiderLayout.setVerticalGroup(
            tabRiderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
            .addGroup(tabRiderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabRiderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("RESPOND", tabRider);

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addContainerGap()
<<<<<<< HEAD
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
=======
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
>>>>>>> 48974dafeae44350d52849e52608034cb842417f
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1114, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(panelProfile);

        jMenuProfile.setBackground(new java.awt.Color(102, 142, 57));
        jMenuProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profiledashboardIcon.png"))); // NOI18N
        jMenuProfile.setText("Profile");
        jMenuProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuProfile.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuProfile.setOpaque(true);
        jMenuProfile.setPreferredSize(new java.awt.Dimension(200, 52));

        jMenuItem3.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profiledashboardIcon.png"))); // NOI18N
        jMenuItem3.setText("View Profile");
        jMenuItem3.setOpaque(true);
        jMenuItem3.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItem3);

        jMenuItemDelete.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItemDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemDelete.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete.png"))); // NOI18N
        jMenuItemDelete.setText("Delete Account");
        jMenuItemDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItemDelete.setOpaque(true);
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItemDelete);

        jMenu.add(jMenuProfile);

        jMenuKYC.setBackground(new java.awt.Color(102, 142, 57));
        jMenuKYC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuKYC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/kycIcon.png"))); // NOI18N
        jMenuKYC.setText("KYC");
        jMenuKYC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuKYC.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuKYC.setOpaque(true);
        jMenuKYC.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuKYC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKYCMouseClicked(evt);
            }
        });
        jMenu.add(jMenuKYC);

        jMenu1.setBackground(new java.awt.Color(102, 142, 57));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(400, 6));
        jMenu.add(jMenu1);

        contactMenu.setBackground(new java.awt.Color(102, 142, 57));
        contactMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contactMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/HelpIcon.png"))); // NOI18N
        contactMenu.setText("Help");
        contactMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        contactMenu.setMinimumSize(new java.awt.Dimension(200, 52));
        contactMenu.setOpaque(true);
        contactMenu.setPreferredSize(new java.awt.Dimension(200, 52));
        contactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMenuMouseClicked(evt);
            }
        });

        AboutUsMenuItem.setBackground(new java.awt.Color(102, 142, 57));
        AboutUsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/AboutUs.png"))); // NOI18N
        AboutUsMenuItem.setText("About Us");
        AboutUsMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AboutUsMenuItem.setOpaque(true);
        AboutUsMenuItem.setPreferredSize(new java.awt.Dimension(200, 52));
        AboutUsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMenuItemMouseClicked(evt);
            }
        });
        AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsMenuItemActionPerformed(evt);
            }
        });
        contactMenu.add(AboutUsMenuItem);

        jMenuItem2.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TermsIcon.png"))); // NOI18N
        jMenuItem2.setText("Terms & Conditions");
        jMenuItem2.setOpaque(true);
        jMenuItem2.setPreferredSize(new java.awt.Dimension(400, 52));
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem2);

        jMenuItem1.setBackground(new java.awt.Color(102, 142, 57));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/contactIcon.png"))); // NOI18N
        jMenuItem1.setText("Contact");
        jMenuItem1.setBorderPainted(false);
        jMenuItem1.setOpaque(true);
        jMenuItem1.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        contactMenu.add(jMenuItem1);

        jMenu.add(contactMenu);

        jMenuLogout.setBackground(new java.awt.Color(102, 142, 57));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        jMenuLogout.setText("Logout");
        jMenuLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuLogout.setOpaque(true);
        jMenuLogout.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenu.add(jMenuLogout);

        jMenuExit.setBackground(new java.awt.Color(102, 142, 57));
        jMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuExit.setMinimumSize(new java.awt.Dimension(200, 52));
        jMenuExit.setOpaque(true);
        jMenuExit.setPreferredSize(new java.awt.Dimension(200, 52));
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenu.add(jMenuExit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // fetchDriverDetails();
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Do you want to add advertisement?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(response == JOptionPane.YES_OPTION){
            try {
                view();
                
            } catch (NullPointerException e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(this, "Please fill the date");
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(response == JOptionPane.NO_OPTION){
            return;

        }
    }//GEN-LAST:event_jButton2ActionPerformed

     public void view(){
        String convertedDate;
        String publishLeave = Leavebox.getSelectedItem().toString();
        String publishGoing = Goingbox.getSelectedItem().toString();
        String publishDate = (String) Datebox.getDate().toString();
        System.out.println(publishDate);
        String day = publishDate.split(" ")[2];
        String month = publishDate.split(" ")[1];
        String year = publishDate.split(" ")[5];
        String convertedMonth = convertMonthIntoString(month);
        int resultHasDigit = convertMonthIntoString(month).length();
        if (resultHasDigit == 1){
            convertedDate = String.format("%s-0%s-%s", year, convertedMonth, day);
        } else{
            convertedDate = String.format("%s-%s-%s", year, convertedMonth, day);
        }
        System.out.println(convertedDate);
        String publishTrunk = Trunkbox.getSelectedItem().toString();
        String publishSeat = Seatbox.getSelectedItem().toString();
        String publishPrice = Pricebox.getText();

        if(!publishPrice.matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Please enter valid price", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(publishPrice.length() > 5){
            JOptionPane.showMessageDialog(this, "Please enter valid price", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!nameValid.nameVerify(publishLeave)){
            JOptionPane.showMessageDialog(this, "Please enter valid leave place", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!nameValid.nameVerify(publishGoing)){
            JOptionPane.showMessageDialog(this, "Please enter valid going place", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else{

            String email = null;
            String phone  = null;
    
            ResultSet rset = new UserController().selectEmail();
            try {
                while(rset.next()){
                    email = rset.getString(1);
                    phone = rset.getString(2);
                }
            } catch (Exception e) {
                // TODO: handle exception
            }
            Driver addDriverDetails = new Driver(0,publishLeave, publishGoing, convertedDate, publishTrunk, Integer.parseInt(publishSeat), Integer.parseInt(publishPrice),null,phone,email);
            DriverController dc = new DriverController();
            int result = dc.insertDriverDetails(addDriverDetails);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Driver details inserted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                table();
    
            }
            else {
                JOptionPane.showMessageDialog(this, "Failed to add driver details.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
}
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            
            String convertedDate;
            String publishLeave = Leavebox.getSelectedItem().toString();
            String publishGoing = Goingbox.getSelectedItem().toString();
            String publishDate = (String) Datebox.getDate().toString();
            System.out.println(publishDate);
            String day = publishDate.split(" ")[2];
            String month = publishDate.split(" ")[1];
            String year = publishDate.split(" ")[5];
            String convertedMonth = convertMonthIntoString(month);
            int resultHasDigit = convertMonthIntoString(month).length();
            if (resultHasDigit == 1){
                convertedDate = String.format("%s-0%s-%s", year, convertedMonth, day);
            } else{
                convertedDate = String.format("%s-%s-%s", year, convertedMonth, day);
            }
            System.out.println(convertedDate);
            String publishTrunk = Trunkbox.getSelectedItem().toString();
            String id = idBox.getText();
            String publishSeat = Seatbox.getSelectedItem().toString();
            String publishPrice = Pricebox.getText();
            if(!publishPrice.matches("[0-9]+")){
                JOptionPane.showMessageDialog(this, "Please enter valid price", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }else if(publishPrice.length() > 5){
                JOptionPane.showMessageDialog(this, "Please enter valid price", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }else if(!nameValid.nameVerify(publishLeave)){
                JOptionPane.showMessageDialog(this, "Please enter valid leave place", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }else if(!nameValid.nameVerify(publishGoing)){
                JOptionPane.showMessageDialog(this, "Please enter valid going place", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
                else{
                    Driver addDriverDetails = new Driver(Integer.parseInt(id),publishLeave, publishGoing, convertedDate, publishTrunk, Integer.parseInt(publishSeat), Integer.parseInt(publishPrice),null,null,null);
                    DriverController dc = new DriverController();
                    int result = dc.editDetails(addDriverDetails);
                    if(result>0){
                        JOptionPane.showMessageDialog(this, "Edited Success");
                        DefaultTableModel model1 = (DefaultTableModel) tblDriver.getModel();
                        model1.setRowCount(0);
                        table();
                    }
    
                }

        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(this, "Please select a row to edit", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void btnDeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDeleteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteFocusGained

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        // DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int i = tblDriver.getSelectedRow();
        TableModel model = tblDriver.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String rideStatus= model.getValueAt(i,7 ).toString();
        if(rideStatus.equals("Active")||rideStatus.equals("Complete")){
            JOptionPane.showMessageDialog(this,"The ride can't be deleted","Error",2);

        }else{
            try {
                Driver d1 = new Driver(id,null,null,null,null,0,0,null,null,null);
                DriverController dc = new DriverController();
                int result = dc.deleteDetails(d1);
                if(result>0){
                    JOptionPane.showMessageDialog(this,"Delete Success");
                    DefaultTableModel model1 = (DefaultTableModel) tblDriver.getModel();
                    model1.setRowCount(0);
                    table();

                }
            } catch (Exception e) {
                // TODO: handle exception
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        int i = tblDriver.getSelectedRow();
        TableModel model = tblDriver.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String rideStatus= model.getValueAt(i,7 ).toString();
        if(rideStatus.equals("Active")||rideStatus.equals("Complete")){
            JOptionPane.showMessageDialog(this,"The ride can't be viewed","Error",2);

        }else{

            try {
                //    User u1 = new User(null, "1", null, null, null, null, null, null, null, null, "2", null, null, null, null, null, null) ;
                Driver d1 = new Driver(id, null, null, null, null, 0, 0,null,null,null);
                DriverController dc = new DriverController();
                ResultSet result  = dc.selectDetails(d1);
                while(result.next()){
                    String dId  = result.getString(1);
                    String dLeave = result.getString(2);
                    String dGoing = result.getString(3);
                    String dDate = result.getString(4);
                    String dTrunk = result.getString(5);
                    String seat = result.getString(6);
                    String price = result.getString(7);
                    // JOptionPane.showMessageDialog(null,dLeave+" " +dGoing +""+ dDate+""+dTrunk+ ""+ seat);
                    Leavebox.setSelectedItem(dLeave);
                    Goingbox.setSelectedItem(dGoing);
                    // Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dDate);
                    java.util.Date dob = new SimpleDateFormat("yyyy-MM-dd").parse(dDate);
                    Datebox.setDate(dob);
                    Trunkbox.setSelectedItem(dTrunk);
                    Seatbox.setSelectedItem(seat);
                    Pricebox.setText(price);
                    idBox.setText(dId);
                    editBtn.setEnabled(true);
                }

            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        int i = tblDriver.getSelectedRow();
        TableModel model = tblDriver.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String rideStatus= model.getValueAt(i,9 ).toString();
        if(rideStatus.equals("Active")){
            Driver d1 = new Driver(id,null,null,null,null,0,0,null,null,null);
            DriverController dc = new DriverController();
            int result = dc.Complete(d1);
            if(result>0){
                // JOptionPane.showMessageDialog(this, "Accepted");
                table();
            }

        }else{
            JOptionPane.showMessageDialog(this,"The ride is not active","Error",2);

        }
        // if()
    }//GEN-LAST:event_completeBtnActionPerformed

    private void activeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeBtnActionPerformed
        int i = tblDriver.getSelectedRow();
        TableModel model = tblDriver.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String rideStatus= model.getValueAt(i,9 ).toString();
        if(rideStatus.equals("Active")){
            JOptionPane.showMessageDialog(this,"The ride is already active","Error",2);

        }else{

            Driver d1 = new Driver(id,null,null,null,null,0,0,null,null,null);
            DriverController dc = new DriverController();
            int result = dc.Active(d1);
            if(result>0){
                // JOptionPane.showMessageDialog(this, "Accepted");
                table();
            }
        }
    }//GEN-LAST:event_activeBtnActionPerformed


    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        int i = rideTable.getSelectedRow();
        TableModel model = rideTable.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        Driver d1 = new Driver(id,null,null,null,null,0,0,null, null,null);
        DriverController dc = new DriverController();

        int result = dc.Decline(d1);
        if(result>0){
            JOptionPane.showMessageDialog(this, "Declined");
            displayBook();

        }
    }//GEN-LAST:event_declineBtnActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        int i = rideTable.getSelectedRow();
        TableModel model = rideTable.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        Driver d1 = new Driver(id,null,null,null,null,0,0,null,null,null);
        DriverController dc = new DriverController();
        int result = dc.Accept(d1);
        if(result>0){
            JOptionPane.showMessageDialog(this, "Accepted");
            displayBook();
        }
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Profile().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuKYCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKYCMouseClicked
        // TODO add your handling code here:
        new KYC().setVisible(true);
    }//GEN-LAST:event_jMenuKYCMouseClicked

    private void AboutUsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsMenuItemMouseClicked

    private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_AboutUsMenuItemActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Terms().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ContactMain().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactMenuMouseClicked

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogoutMouseClicked
        int response = JOptionPane.showConfirmDialog(this,"Do you want to logout?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
            new UserController().changeStatus(null);
            dispose();
            JOptionPane.showMessageDialog(this, "Logged out successfully");
            new Login().setVisible(true);
        }
        else if(response == JOptionPane.NO_OPTION){
           return;
            
        }
        
       
    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Do you want to exit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
            new UserController().changeStatus(null);
            dispose();
        }
        else if(response == JOptionPane.NO_OPTION){
           return;
            
        }
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void LeaveboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeaveboxActionPerformed

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Do you want to delete your account?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(response == JOptionPane.YES_OPTION){
            UserController uc = new UserController();
            DriverController dc=  new DriverController();
            dc.cancelAllRide();
            dc.deleteallDetails();
            int result = uc.deleteAccount();
            if(result>0){
                JOptionPane.showMessageDialog(null, "Account Deleted");
                dispose();
                new Login().setVisible(true);
            }
        }
        else if(response == JOptionPane.NO_OPTION){
            return;

        }

    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void fullBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Do you want to fill the seat?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            int i = tblDriver.getSelectedRow();
        TableModel model = tblDriver.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        Driver d1 = new Driver(id,null,null,null,null,0,0,null,null,null);
        
            DriverController dc = new DriverController();
            dc.fullSeat(d1);
            JOptionPane.showMessageDialog(this, "Seat Filled");
            table();
        }
        else if(response == JOptionPane.NO_OPTION){
            return;

        }
    }//GEN-LAST:event_fullBtnActionPerformed


    /**
     * @param evt
     */
                                             

    
    public void table(){
        try {
            // Driver d1 = new Driver(null,null,null,null,0,0);
            DriverController dc = new DriverController();
            ResultSet rset = dc.fetchDriverDetails();
            DefaultTableModel model = (DefaultTableModel) tblDriver.getModel();
            model.setRowCount(0);
            while(rset.next()){
                String SN = rset.getString(1);
                String Leave = rset.getString(2);
                String Going  = rset.getString(3);

                String date = rset.getString(4);
                
                String trunk = rset.getString(5);
                String seat = rset.getString(6);
                if(seat.equals("0")){
                    seat = "Full";
                }
                
                String price = rset.getString(7);
                String rideStatus= rset.getString(10);
                String email = rset.getString(11);
                String phone  = rset.getString(12);
                

                // JOptionPane.showMessageDialog(null,SN + Leave+Going+date+trunk+price);
                Object[] row = {SN,Leave,Going,email,phone,date,trunk,seat,price,rideStatus};
                model.addRow(row);
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block

        } 
    }

    public void displayBook(){
        ResultSet result = new DriverController().showBook();
        DefaultTableModel model  =(DefaultTableModel) rideTable.getModel();
        model.setRowCount(0);
        try {
            while(result.next()){
                String SN = result.getString(1);
                String Leave = result.getString(2);
                String Going  = result.getString(3);

                String userName = result.getString(4);
                String phone = result.getString(5);
                String booking = result.getString(6);

                Object[] rows = {SN,Leave,Going,userName,phone,booking};
                model.addRow(rows);

                
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new seat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsMenuItem;
    private javax.swing.JFrame BankTop;
    private com.toedter.calendar.JDateChooser Datebox;
    private javax.swing.JComboBox<String> Goingbox;
    private javax.swing.JComboBox<String> Leavebox;
    private javax.swing.JTextField Pricebox;
    private javax.swing.JComboBox<String> Seatbox;
    private javax.swing.JComboBox<String> Trunkbox;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton activeBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton completeBtn;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JButton declineBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton fullBtn;
    private javax.swing.JTextField idBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenu jMenuKYC;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuProfile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelLogoTop1;
    private javax.swing.JLabel labelLogoTop3;
    private javax.swing.JLabel labelWhiteHLine3;
    private javax.swing.JPanel panelEditProfile1;
    private javax.swing.JPanel panelEditProfile3;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JTable rideTable;
    private javax.swing.JPanel tabDriverTab;
    private javax.swing.JPanel tabRider;
    private javax.swing.JTable tblDriver;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    private String convertMonthIntoString(String month) {
        return switch(month){
            case "Jan" -> "1";
            case "Feb" -> "2";
            case "Mar" -> "3";
            case "Apr" -> "4";
            case "May" -> "5";
            case "Jun" -> "6";
            case "Jul" -> "7";
            case "Aug" -> "8";
            case "Sep" -> "9";
            case "Oct" -> "10";
            case "Nov" -> "11";
            case "Dec" -> "12";
            default -> "00";
        };
    }

    
}
